### ISSUE TITLE
How to push the data from kapua to another data base

### ISSUE THREAD

**Issue by dineshkumar4728** [eclipse/kapua#1093]
Hi all,
         I want to push  data from kapua to another database , apart from rest api please give me any possible solution. Is there any  documentation for this please send.
  
  Thank you
  - Dinesh kumar

**Comment by dineshkumar4728** [comment]
HI @ctron @kartben ,
     Can you please provide any possible ways for the above querry.
 Thank you

**Comment by kamir** [comment]
Hello @ctron, @kartben, 
after our very informative chat with Benjamin - Thanks again for your support! - and a follow-up code walk through it is still not completely clear to us, where to start with an implementation of a custom DataStore. Is there any design document about **Kapua Data Persistence aspects** available?

This presentation: https://wiki.eclipse.org/images/2/26/1610_Kapua_Status.pdf
shows the DataStorage Service on page 5 besides the DataRegistry Service and a future DataUsage Service (which as an amazing idea!).

Our question is: What kind of data is stored in the NoSQL database (Elasticsearch at this time)?
Is it correct, that only the messages are persisted that way?

Our vision is, to have a SOLR-cluster or an HBase cluster as a long term persistence layer, provided by a proper data management platform. Since each message can be seen as a datapoint already one can easily map them to a time series database - which will be OpenTSDB in our case.

Having this in mind we want to offer some energy towards an implementation of a custom DataStorage service. 

If I would have to continue alone, I would try to get my head around the current code and implement an "In-Memory Lucene based store".

But maybe there is already some model or tooling available from which we can get stubs / templates or code-generation capabilities. 

Any hint is welcome!
Cheers,
Mirko & Nehme

**Comment by stefanomorson** [comment]
Hi,

I'll try to go through your comment trying to give some answers and suggestions.

> Our question is: What kind of data is stored in the NoSQL database (Elasticsearch at this time)?

The NoSQL data store provides the persistency layer for the data messages. Generally speaking a data message  contains a collection of key-value pairs sent to the messaging layer by a connected device. We call metric the "key" part of the couple. The message can additionally contain raw data. 
Typically, data in the message carrie values gathered by sensors in the field. A data message has additional properties like the tenant it belongs to, the clientId of the device that sent the message, the time the message has been sent and received, the geo referencing and the channel (not all mandatory). 
The datastore contains also registries. They are used to quickly retrieve meta information regarding the messages in some use cases; they are automatically populated by the data store service based on the values in the messages.  There are three types of registries: the ClientInfo registry contains the list of clientId that published some data, the ChannelInfo registry contains the list of channels where data messages have been published, MetricInfo registry contains the list of published metrics.

> Is it correct, that only the messages are persisted that way?

Basically yes, currently we persist data messages plus registry entries. Each category of data has its own Elastcsearch type (mapping). Data messages and registry entries are stored in separated Elasticsearch indexes.

> Our vision is, to have a SOLR-cluster or an HBase cluster as a long term persistence layer, provided by a proper data management platform. Since each message can be seen as a datapoint already one can easily map them to a time series database - which will be OpenTSDB in our case.

That sounds good. Actually there are a couple of possible solutions, let me try to explain.

**First option** is the development of a full featured implementation of the datastore (the comment from @riccardomodanese  above). With this approach you will implement a tighter integration with the Kapua service API and the Kapua Datastore service data model.  On the other hand what you gain is the integration with other Kapua components. 
Regarding the deployment, with this option you currently have to change the pom files and some configuration files of the application components (console, API, broker) in order to pick-up the new implementation in place of the default one. The platform is currently configured to use the Elasticsearch implementation. Depending on your use case this can be feasible or not.

**Second option** is to use a Camel route. Since Kapua messaging uses Camel, it is possible to redirect data messages to an "external" endpoint, in this case the HBase cluster or the SOLR-cluster. The datastore in this case will be skipped. For Camel components refer to Camel documentation ([1]).
Routes are specified in a Camel configuration file. You may also need to write some code in a bean to convert messages coming from the Kapua messaging in the format that is more appropriate for HBase or SOLR.
From the deployment point of view this solution is lighter compared to the previous since it requires a camel route and probably a jar file containing the bean. The latter needs to be deployed in the class path of the broker. With this option you don't need to change the application build configuration.

> Having this in mind we want to offer some energy towards an implementation of a custom DataStorage service.

That would be great!

> But maybe there is already some model or tooling available from which we can get stubs / templates or code-generation capabilities.

There's no tooling to generate code unfortunately. The best thing I can suggest is to look at the current implementation of the datastore. I would first look at the datastore APIs under the project **kapua-datastore-api** ([2]). These are the APIs used by all other Kapua compoenents to interact with the datastore.  Then you should look at the Elasticsearch implmentation that is contained in the prokect **kapua-datastore-internal** ([3]).

Hope this can help.

[1] http://camel.apache.org/components.html
[2] https://github.com/eclipse/kapua/tree/develop/service/datastore/api
[3] https://github.com/eclipse/kapua/tree/develop/service/datastore/internal

**Comment by Coduz** [comment]
Hi @kamir ,

Is this still an issue? 
If not we can close it, since it's been a while with no updates on this.

Regards, 

_Alberto_

**Comment by menoz** [comment]
Hi all,
sorry for reopening this issue, but I'm really interested in @stefanomorson 's "second option" (editing Camel configuration in order to add/substitute endpoints): I'd like to store messages in postgres (and maybe other endpoints), and editing Camel config would be my best option now.
Can you please point me in the right direction, in order to (at least) find the right files to understand the whole process and finally edit it?
I've seen an interesting assembly/broker/configurations/camel.xml config file , is this the right place to start?
And what would be the following steps?

Thank you very much,
Daniele

**Comment by lorthirk** [comment]
Also @riccardomodanese could have some helpful insights!

**Comment by riccardomodanese** [comment]
Hi Daniele, yes the assembly module is the right direction to point to.
There are 2 different files, the [camel.xml](https://github.com/eclipse/kapua/blob/develop/assembly/broker/configurations/camel.xml) (as you mentioned) and the [camel-routes.xml](https://github.com/eclipse/kapua/blob/develop/assembly/broker/configurations/camel-routes.xml).
The second one is loaded by [CamelKapuaDefaultRouter](https://github.com/eclipse/kapua/blob/develop/broker-core/src/main/java/org/eclipse/kapua/broker/core/router/CamelKapuaDefaultRouter.java) and it's the entry point for the Kapua internal message routing (I mean the messages handled by the platform).
If you want to manage other kind of messages or handle the same kind in a differrent way you can modify this file.
It's a custom wrapper we developed to generate Camel Routing Slip [Routing Slip](http://camel.apache.org/routing-slip.html).


Just to give you a snippet you can add a tag after the datastore endpoint (or replace it) like this:
```
<simpleEndPoint>
   <regex>.*</regex>
   <endPoint>bean:kapuaDataConverter?method=convertToData,bean:yourBean?method=yourMethod</endPoint>
</simpleEndPoint>
```
and so implements your logic inside the new bean.

Otherwise, you can remove the Kapua Slip Processor modifying the camel.xml and then adapt Camel configuration as you need (the camel.xml it's a "standard" "Spring/Camel" configuration file).
But, in that case, you need to add the Kapua default internal message routing.

I hope this helps you!

**Comment by menoz** [comment]
Thank you @riccardomodanese ! That's exactly what I was looking for, and thanks also for the accurate explanation.
