### ISSUE TITLE
Package Name And Version Ignored At Installation

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1125]
When user tries to install a package on Kura through Kapua, _default_ values for package name and version are used (see at the screenshots).

Testflow: 
1. Login as kapua-sys
2. Connect live Kura device to Kapua
3. Go to Devices (select the connected Kura device) -> Packages -> In Progress -> Install
4. Enter package URL (e.g. from Eclipse Marketplace), package name and version
5. Click submit. 
**Although user enters non-default values for pacakge name and version,d efualt ones are used (look at screenshot No. 3).**

Screenshot No. 1 (Enter package URL, name and version): 
<img width="1440" alt="screen shot 2017-12-05 at 09 36 11" src="https://user-images.githubusercontent.com/15121999/33597730-a3e66cb4-d9a0-11e7-8fbe-8ace877eb47b.png">

Screenshot No. 2 (Refresh whole page, as refresh button does not work):
<img width="1435" alt="screen shot 2017-12-05 at 09 37 33" src="https://user-images.githubusercontent.com/15121999/33597746-aca02ba6-d9a0-11e7-906d-5cd7abe45dab.png">

Screenshot No. 3 (Look at the highlighted package - default values for name and version are used): 
<img width="1440" alt="screen shot 2017-12-05 at 09 37 44" src="https://user-images.githubusercontent.com/15121999/33597761-b3490efa-d9a0-11e7-9f39-698710f95304.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

The package names and versions shown in the packages view are the name inside the `.dp` package. 
The name and version provided when installing is the reference name that you'll use if you run the installing in two step (first download and then install), because Kura uses that name to save the file. On receiving the `install` command, Kura looks at the available packages and search for the provided name and version. If it founds any matching it'll install it right away. 

Actually I think this should be managed more on the Kura side, which can eventually override the package name and version with the one that it receives from the platform. 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Closing due to upper comment.
