### ISSUE TITLE
Wrong Message When Adding Same Targets in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1172]
When user tries to add same devices (targets) twice to a job, Kapua always reports _**Targets Successfully Added**_, altohugh it should report that certain devices have already been added. 

Testflow: 
1. Login as kapua-sys
2. Go to Devices, add two devices (e.g. device1 and device2)
3. Go to Jobs, create a job (e.g. job1) and try to add both devices (targets) to this job. 
**Try to add same devices multiple times. Kapua will always return info: _Targetes Successfully Added_.**

<img width="1439" alt="screen shot 2017-12-11 at 13 31 26" src="https://user-images.githubusercontent.com/15121999/33831330-e995a9e2-de77-11e7-8024-5d2b77cc9adf.png">

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
By design, the functionality adds a new target in the list only if the target it is not already present. The same can be said if a list of targets are selected to be added.

#### Expected results:
If the list of newly created targets is empty the notification message should report that "No new targets have been selected"

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved in PR #1355 .
