### ISSUE TITLE
User Cannot Create Roles/Groups/Device/Jobs/Users Although it Has All Permissions Needed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1360]
User cannot create new Role/Group/Device/Job/User, although it has all the permissions needed for the operation (read, write and delete). Kapua returns error, saying: _**User doesn't have permission to perform this action.**_

Testflow: 
1. Login as kapua-sys
2. Go to Child Accounts, create a child account (e.g. kapua-child1)
3. Add a user to this child account (e.g. kapua-user1) 
4. Go to kapua-child1 account and select kapua-user1, add _**read, write**_ and _**delete**_ permissions for Roles, Access Groups, Devices, Users and Jobs to it.
5. Logout as kapua-sys and login as kapua-user1
6. Go to Roles/Jobs/Access Groups/Devices/Users and try to create an item. 
_**When user tries to do this, Kapua returns error described above and as shown bellow.**_

Screenshot (this is just an example of the error. Same thing happens to all the groups mentioned above): 
<img width="1313" alt="screen shot 2018-02-05 at 13 43 50" src="https://user-images.githubusercontent.com/15121999/35807756-fba7166a-0a83-11e8-8896-7c76ec8c433f.png">

Browsers used:
- Google Chrome (Version 64.0.3282.119 (Official Build) (64-bit)))
- Safari (Version 11.0.3 (13604.3.5))
- Mozilla Firefox (58.0.1  (64-bit))
- Opera (Version 50.0.2762.67)

**Comment by lorthirk** [comment]
So, While working on this I noticed that:

- Role creation is actually broken, and I fixed it in the branch mentioned at the end of this comment
- Devices, Groups and and Jobs seems to be fine
- Users are broken as well, but this is somewhat "by design" since we create a credential for a new user at the same time; so in order to create a new User also credential:write is needed. We could fix this when we establish a mechanism to enable and disable CRUD buttons according to permissions

Roles are fixed in `fix-restricted_permission_actions` branch

**Comment by LeoNerdoG** [comment]
@lorthirk I have checked the branch and current behaviour is: 
1. User can successfully add, edit and remove all of the above items (jobs, roles, groups, users, jobs)
2. When deleting a user, Kapua still reports error: _**User doesn't have permission to perform this action.**_ but deletion is successfull. 

Screenshot No. 1 (Deleting user):
<img width="1424" alt="screen shot 2018-02-28 at 10 28 56" src="https://user-images.githubusercontent.com/15121999/36780336-faf0cd64-1c72-11e8-8f29-a0e922472368.png">

Screenshot No. 2 (Error pops-up but user is deleted successfully):
<img width="1431" alt="screen shot 2018-02-28 at 10 29 01" src="https://user-images.githubusercontent.com/15121999/36780347-071e6894-1c73-11e8-90eb-c423c359398f.png">

3. When deleting a role, it gets successfully deleted, but the info message is wrong (it says _**Permission association successfully revoked**_ but it should be: _**Role successfully deleted**_)

Screenshot No. 3 ():
<img width="1428" alt="screen shot 2018-02-28 at 10 29 53" src="https://user-images.githubusercontent.com/15121999/36780410-365f2a94-1c73-11e8-98de-72a26612a95d.png">

4. When user selects a role and it navigates to _**Granted Users**_ Kapua reports an error (look at screenshot bellow). 

<img width="1428" alt="screen shot 2018-02-28 at 10 30 36" src="https://user-images.githubusercontent.com/15121999/36780449-544906f6-1c73-11e8-89b1-abb994adc6a8.png">

Strictly speaking, this issue is resolved, only error messages have to be resolved.

**Comment by lorthirk** [comment]
First three points are fixed. The fourth one also should be ok, but now for the Granted Users tab to show itself the user needs read permissions un users, roles and access_info.

Update in `` branch (you probably want to download it again since, while the name is the same, is actually a new branch).

**Comment by LeoNerdoG** [comment]
I have verified that this issue is fixed.
