### ISSUE TITLE
Disconnect Filter Option in Devices Not Working Properly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1395]
If user manually adds device to Kapua, they are automatically labeled as _**Disconnected**_, which is OK, becasue these devices are not active. 
But if user in filter option selects _**Disconnected**_ (in Device Connection Status), these devices are not listed - only previously live devices (and later disconnected) are listed as Disconnected. 

Testflow: 
1. Login as kapua-sys
2. Go to Devices and add several devices (e.g. device1, device2,...)
3. Connect a live Kura device to Kapua and after it successfully connects, disconnect it
4. In Device filter menu select _**Disconnected**_ in _**Device Conncetion Status**_
**In Device list only previously connected (live) devices will appear but not the manually created ones.**

Screenshot No. 1 (Device Connection Filter set to _**ANY**_ - result is OK):
![screen shot 2018-02-13 at 14 41 04](https://user-images.githubusercontent.com/15121999/36153012-3625c8fa-10cd-11e8-808c-e4e2f538c001.png)

Screenshot No. 2 (Device Conncetion Filter set to _**Disconnected**_ - result not ok ):
![screen shot 2018-02-13 at 14 41 14](https://user-images.githubusercontent.com/15121999/36153017-37d0def6-10cd-11e8-8729-dec57820a744.png)

Browsers used:
- Google Chrome (Version 64.0.3282.140 (Official Build) (64-bit)
- Safari (Version 11.0.3 (13604.3.5))
- Mozilla Firefox (58.0.2  (64-bit))
- Opera (Version 51.0.2830.26)

**Comment by ct-goranpalibrk** [comment]
@lorthirk @muros-ct @LeoNerdoG Device Filter Panel is working properly because it returns values which are not null, and when we manually add new device, his connection_id is null so that device is not connected or disconnected either. One suggestion would be that we put new item in combo-box named UNKNOWN which would return devices which have connection_id=null (that are not disconnected or connected) and their status icon should have different color(e.g. gray). But if this suggestion is okay, then we have to resolve problems with predicates which are comparing null values.

**Comment by lorthirk** [comment]
@ct-goranpalibrk you're right. Creating a new UNKNOWN status in `GwtDeviceConnectionStatus` that, when used in a filter, returns the devices with `connectionId == null` seems the best option.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
