### ISSUE TITLE
Removing default user (kapua-sys) or even changing the password is making Kapua non functional

### ISSUE THREAD

**Issue by Laurent-ASGW** [eclipse/kapua#1475]
Hello,

To bring some security in the system we had plan to remove the default user and password are these are known in the Internet and by acquiring those someone can take control of the Kapua instance.

So we have removed the default-user (or even changing the default password leads to the same result) but this leading to a non-functional system as the connection to the MQTT broker are made using this defaults without any simple way to change it. We are working on that since 2 weeks but even before proposing a solution, we would like to submit the issue to the community.

**Comment by riccardomodanese** [comment]
Hi, 
did you change also 

[commons-properties account](https://github.com/eclipse/kapua/blob/develop/commons/src/main/resources/kapua-environment-setting.properties#L14) 
[commons-properties username](https://github.com/eclipse/kapua/blob/develop/commons/src/main/resources/kapua-environment-setting.properties#L15)

[mqtt-transport username](https://github.com/eclipse/kapua/blob/develop/transport/mqtt/src/main/resources/mqtt-client-setting.properties#L14)
[mqtt-transport password](https://github.com/eclipse/kapua/blob/develop/transport/mqtt/src/main/resources/mqtt-client-setting.properties#L15)

**Comment by lorthirk** [comment]
About the password: did it contain `<` or `>` by any chance?

**Comment by tovantti** [comment]
If default "kapua-password" is changed in console UI, then executing commands in Kura fails because MQTT client doesn't authenticate as default credentials are read from class path property file.

In order to change the password without creating new Docker image, Kapua console must be started with "kapua.config.dir" system property pointing to mounted configuration directory. This would give possibility to add a property file with "transport.credential.password" setting.

I can not find any documentation about using non default system account.

**Comment by stefanomorson** [comment]
@tovantti, component configurations can be overriden either in a custom configuration file by system property kapua.config.dir as you correctly pointed out or by setting the corresponding system property one by one. 
The procedure that you described is correct, where you finally successful to change the password at the end ? Tanks for reporting the lack of documentation we'll provide a fix.

**Comment by Coduz** [comment]
Hi @Laurent-ASGW ,

You still need help on this? 

Regards, 

_Alberto_
