### ISSUE TITLE
Number of Characters in Command Window in Devices Not Limited

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1715]
When entering commands into Command field, problem emerges, if command is too long and contains special symbols (some of theme work like line "breakers" - look at the screenshot).

Testflow: 
1. Login as kapua-sys or any other user with proper priviliges (Broker:ALL, Device:ALL, Device_management:ALL, Device_lifecycle:ALL)
2. Connect a live Kura device to Kapua (e.g. device0)
3. Go to Devices, select device0 and go to its Command tab
4. Enter a very long useles command (e.g. 123456789ertyuifghjvb<.,<<.#$%&'(UYFVBN_:;>_:;@‹›€ı”ÓÔˇ¿È.-.1,2-3.,-3.,1-23.,1-.,-.,23>:_>;_:>;_..1-23....)
**Observe how Kapua puts this command into multiple lines (try with a very long command - as seen on screenshot).**

![screen shot 2018-05-18 at 12 59 14](https://user-images.githubusercontent.com/15121999/40231438-79dd5d48-5a9b-11e8-9d65-c99691038b22.png)

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 53.0.2907.57)

**Comment by ct-ajovanovic** [comment]
Hi @Coduz  @lorthirk 
Can you take a look at this? 
It seems there is no limit for the Command field, and no validation?
What should the limit be? And the validation regex? What rules should it follow?
Thanks
_Aleksandra_

**Comment by Coduz** [comment]
Hi @LeoNerdoG and @ct-ajovanovic ,

Until now there is no validation on the actual `CommandInput` object (besides `null` check).

Using a regex to validate the `commandInput.command` is pretty tricky since it could be any of the UNIX command (and more, depending on the OS running on the device). 

I think that we can set a UI limit (maybe 1024) with an error that explains that if you need to run long commands, you can put all commands in a `.sh` file and upload (zipped) it in the `file` field. 

On the error message we can manage in a better way the overflow of the content. Or maybe, to make things simpler, just do not mention the specific command that has been run, but refer to a generic command.

Is that good for you? 

Regards,

_Alberto_

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
I think your proposals are good, so @ct-ajovanovic you can start fixing this 😸 

Leo

**Comment by LeoNerdoG** [comment]
I have verified that this issue has bee resolved. @muros-ct you can put this in "Done".
