### ISSUE TITLE
Multiple Refresh Buttons in Dataview

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1722]
After adding some new features into Dataview, there are now multiple refresh buttons for the same thing (refreshing "By Device" and "By Asset" list - look at the screenshots). I think the bottom (blue, circled - look at the screenshot) and ones in Last Post Date should be removed. 

Testflow: 
1. Login as kapua-sys or any other user with proper permissions
2. Connect live Kura device to Kapua
3. Go to Data -> By Device/By Asset and observe all the refresh buttons.

Screenshot No. 1 (Duplicate refresh button in "By Device" list):
![screen shot 2018-05-21 at 12 26 02](https://user-images.githubusercontent.com/15121999/40303829-b6a0ac8e-5cf4-11e8-9f21-0f4b51db34f7.png)

Screenshot No. 2 (Duplicate refresh button in "By Asset" list):
![screen shot 2018-05-21 at 12 26 08](https://user-images.githubusercontent.com/15121999/40303832-b98fef40-5cf4-11e8-808b-c48bc18e2427.png)

Screenshot No. 3 (Refresh button in last Post Date column):
![screen shot 2018-05-21 at 12 26 28](https://user-images.githubusercontent.com/15121999/40303840-bc174d94-5cf4-11e8-84cb-41fb63139352.png)

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 53.0.2907.57)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

The refresh button on the column "last post date" is by design. 

This is required to update the last post date for a single device/asset/topic. 
The scenario is that with a large number of topic/device/asset they can take long to load. So we put a timeout on the loading process of those dates. 

A user can manually refresh the time of the last post date in case of data not being loaded in the first time.

Regards,

_Alberto_

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
