### ISSUE TITLE
No "No Tag" Option in Device Filters

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1754]
When user adds or creates a device, this device can be tagged with multiple tags or none. So if user wants to search devices that are tagged with certain tag, he finds this tag in Tag part of Filter panel on the right.  But if user wants to search devices that _belong_ to _No Tag_, there is no such option (although this is a valid setting for a device).

**Testflow:** 
1. Login as kapua-sys or any other user with proper permissions
2. Go to Tags, add several tags (e.g. tag1, tag2...)
3. Go to Devices, add several devices (e.g. device1, device2...)
4. Add several tags to every deveice except one, that should remain "tagless". 
**If user wants to filter out the device, that has no tags, that is not possible.** 

**Expected behavior:**
 - There should also be a _No Tag_ option in the Tag part of Device Filter

**Screenshot No. 1 (Current options of Tag Filter in Devices):**
![screen shot 2018-05-29 at 11 50 53](https://user-images.githubusercontent.com/15121999/40651677-9576cd3e-6336-11e8-9119-aad15d92b4e6.png)

**Screenshot No. 2 (How should be - example for Group Filter):**
![screen shot 2018-05-29 at 11 51 00](https://user-images.githubusercontent.com/15121999/40651680-97ad4d80-6336-11e8-9950-6a3bcb654651.png)

**Version of Kapua:**
 - 1.0.0 SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console 
[ ] REST API
[ ] Message Broker
[ ] - Others

**Browsers used:** 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 52.0.2871.64)

**Comment by ct-goranpalibrk** [comment]
@Coduz In this issue I tried same method as others for filtering queries which are comparing values with Predicates in GwtKapuaModelConverter classes but here that is not possible because we have lists of Tag ID's  and we can't compare it with one predicate. Do we maybe have some similar case, with comparing lists with predicates or not?

**Comment by Coduz** [comment]
Hi @ct-goranpalibrk ,

This is currently not possible for the reasons you mentioned. 

We need to add the support to `NOT IN` clause in `ServiceDAO`, and make the query similar to:
`SELECT * FROM dvc_devices d WHERE d.tagIds NOT IN ({list of all tag Ids})`

I'll assign also to me, so I can put the changes required on the `ServiceDAO` to support this. 

Then I'll let you implement the UI side of the thing.

Is this ok for all?

Regards 

_Alberto_

**Comment by ct-goranpalibrk** [comment]
@Coduz  Yes, that is great, thanks.

**Comment by Coduz** [comment]
Hi all,

I've tried to play a bit around this, but with no success. 
I'll stop working on this to give priority to other stuff and then I'll get back to this.

Regards, 

_Alberto_

**Comment by muros-ct** [comment]
I worked on this issue last couple of days. I thought it can be solved, but I think it can't be.
By design Device Registry Service and Tag Service are two separate services that are not dependent of each-other. But on database level dvc_device table is connected to tag_tag table by many to many table dvc_device_tag. This makes them dependent on database level.
On the other hand, code level dependency between services is not allowed. By not being allowed, we can not make ManyToMany relationship on JPA level. As this relationship is not available, queries with left outer join are not possible and thereby it is not possible to query on devices that have no tag, but is possible to query on those that have a specific tag.

Thereby I conclude that implementation of this functionality is not possible,  unless we tightly couple    Device Registry and Tag service.

@Coduz can you confirm?

**Comment by Coduz** [comment]
Hi @muros-ct,

I've also tried to find a way to get the device queried properly, but with no success.
Main difficulty for me was that I was not able to query for all device which had the `ElementCollection` empty.

I think that this functionality for now can be post poned. It still can be achieved by selecting all devices and discard the ones that don't have elements. This could be something that we can do on the GwtDeviceRegistry, if we really want to have this.

Regards ,

_Alberto_

**Comment by muros-ct** [comment]
@LeoNerdoG shall we close this issue? It would mean a workaround approach to this single grid and it might cause problems when we have many devices.

**Comment by LeoNerdoG** [comment]
@muros-ct Although this would be a nice feature, I think it would take too much time and it is not "critical" for now. I am closing. can you or @Coduz please label it with "WONTFIX" label?
