### ISSUE TITLE
Every Schedule Counted Twice in Jobs 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1760]
Every schedule that user makes for a certain Job is counted twice. 

**Testflow:**
1. Login as kapau-ys or any other user that has proper permissions
2. Go to Jobs, create a job (e.g. job1)
3. Select job1 and add severa schedules to it (e.g. sch1, sch2...)
**Observe, how Kapua counts every schedule twice (bottom right corner of Schedule window).**

**Expected behavior**
Every schedule should be counted once and not twice.

**Screenshot No. 1 (Kapua shows that there are two pages of schedules):**
![screen shot 2018-05-31 at 15 49 42](https://user-images.githubusercontent.com/15121999/40786094-87ea780e-64ea-11e8-813d-fcf316d60ed8.png)

**Screenshot No. 2 (After changing to page 2, there is nothing):**
![screen shot 2018-05-31 at 14 41 33](https://user-images.githubusercontent.com/15121999/40786089-8634aade-64ea-11e8-9e4c-8540302a86b7.png)
**Version of Kapua**
 - 1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console 
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 53.0.2907.57)

**Comment by ct-goranpalibrk** [comment]
The problem in this issue is that totalLength counts double value of Schedules in JobScheduleGrid. I am not sure how to solve that because count method which is used in this method is the same as in all GwtServiceImplementations, also in TriggerServiceImpl this method count is used in the same way like in other ServiceImplementations. Method query returns exact value, but count return double value.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has bee resolved with PR #1865.
