### ISSUE TITLE
Getting Started (can't start kapua-elasticsearch)

### ISSUE THREAD

**Issue by VitalijVV** [eclipse/kapua#1763]
I am try Getting Started Kapua:
`($ docker run -td --name kapua-elasticsearch -p 9200:9200 -p 9300:9300 elasticsearch:5.4.0 -Ecluster.name=kapua-datastore -Ediscovery.type=single-node -Etransport.host=_site_ -Etransport.ping_schedule=-1 -Etransport.tcp.connect_timeout=30s)`

But I can't start kapua-elasticsearch in Docker. 
The result of 'docker inspect kapua-elasticsearch' command is 'Status: exited' and 'ExitCode: 64'

```
"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 64,
            "Error": "",
            "StartedAt": "2018-06-04T13:33:14.1229195Z",
            "FinishedAt": "2018-06-04T13:33:15.929518Z"
        },
```

**Comment by lorthirk** [comment]
Hi,

an error log would be useful. Could you please post the output of `docker logs kapua-elasticsearch`?

**Comment by VitalijVV** [comment]
Please, you can see below:

starts elasticsearch

Option                Description
------                -----------
-E <KeyValuePair>     Configure a setting
-V, --version         Prints elasticsearch version information and exits
-d, --daemonize       Starts Elasticsearch in the background
-h, --help            show help
-p, --pidfile <Path>  Creates a pid file in the specified path on start
-q, --quiet           Turns off standard ouput/error streams logging in console
-s, --silent          show minimal output
-v, --verbose         show verbose output
ERROR: setting [cluster] must not be empty,

**Comment by lorthirk** [comment]
I know it might sound odd, but there must be something strange in the command you're using to start the container. Exit Code 64 means exactly "command line usage error", and the output you provided shows that Elasticsearch didn't understand the `-Ecluster.name=kapua-datastore` environment variable.

At this point it would could be useful to have the whole `docker inspect` output; please bear in mind, however, that this is all on Elasticsearch side since that image has no implementations at all from Kapua.

**Comment by Coduz** [comment]
Hi @VitalijVV ,

do you need more help on this?
If not this will be closed in few days.

Regards,

_Alberto_
