### ISSUE TITLE
Should Users In Kapua Be Able To Upload Their Own .dp Packages?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2120]
**Is your feature request related to a problem? Please describe.**
Personally I haven't encountered a problem with this issue, but someone that is building their own deployment package (.dp) for Kura, could. 

**Describe the solution you'd like**
I suggest a field/tab is added as this is the case in Kura (look at Screenshots No. 2 & 3) - this would enable user to add their own .dp files directly to Kura device through Kapua - for now user can only deploy package that has a URL I know this could potentialy be a security issue but nevertheless It hink it would be a good feature.

**Describe alternatives you've considered**
/

**Screenshot No. 1 (current situation in Kapua):**
![screen shot 2018-10-15 at 13 20 14](https://user-images.githubusercontent.com/15121999/46948515-a5bec600-d07e-11e8-919d-b0c03fe61eb7.png)

**Screenshot No. 2:**
![screen shot 2018-10-15 at 13 10 27](https://user-images.githubusercontent.com/15121999/46948908-e965ff80-d07f-11e8-9925-afc8cc8f8bab.png)

**Screenshot No. 3:**
![screen shot 2018-10-15 at 13 10 32](https://user-images.githubusercontent.com/15121999/46948913-eb2fc300-d07f-11e8-846d-4216b5c4f202.png)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

there was once the capability to upload directly to the device `.dp` files from local computer using Everyware Cloud. 

This has been changed with the introduction of the `DEPLOY-V2`. This has caused the deprecation of local file upload since the download is performed asynchronously and it should be available. We currently we don't have a service to host a file uploaded from the user.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Due to upper comment I am closing this issue.
