### ISSUE TITLE
Remote IP Parameter In Devices Not Correct?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2228]
There is a "Remote IP" paramter, that is wrong (?) in my case, because my device's IP is 10.19.40.105 and the remote IP is 192.168.48.1. Why is this IP like that? Should this be the same as "IP Address" paramter in

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Connect a live Kura device to Kapua (e.g. device0) 
3. Go to Devices, select device0 and observe "Connection Information" in Description tab. 
**There is "Remote IP" parameter that I do not understand why it has this particular IP**

**Expected behavior**
Shold Remote IP have same value as IP Address parameter? 

**Screenshots**
![screenshot 2018-12-05 at 09 34 22](https://user-images.githubusercontent.com/15121999/49501660-b0722c00-f873-11e8-9aaa-5e679b1d49e9.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by Coduz** [comment]
Hi @LeoNerdoG 

The columns on the grid are values that the devices sends in the birth. Those represents the IP of the network interfaces of the device.

The value you highlighted is the remote IP of the MQTT connection.

You should see the two ip addresses also in the description tab alongside other values. 

We may want to improve this making more clear setting the _Remote IP_ in the column instead of the current value. Show the _Remote IP_ makes more sense IMO.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
I have verifeid that this issue has been resolved.
