### ISSUE TITLE
TextFieldValidator for FieldType.PASSWORD regex bug

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#2242]
**Describe the bug**
The current regex used to validate the password when creating a new _Credential_ does not mark as valid this password:

`>}tN9KP(Rn_Vz`

which has the minimum requirements for a password to be valid.

**To Reproduce**
1 . Open the user view 
2. Go to the credential tab
3. Create a new credential of type passowrd with the given password

**Expected behavior**
The password should be marked as valid

**Screenshots**
_None_

**Version of Kapua**
Kapua 1.0.x

**Type of deployment**
[x] Local Vagrant deployment
[x] Docker
[x] Openshift (in its variants) 
[x] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Additional context**
Somewhat related to #2241

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
I have been working on this Regex more than a year ago. The reason why this password is "invalid" is that there are ">" and "}" symbols in it. 

Because there are no specification as what is a "special character" I have set that only following symbols are permitted: $%^&+=!~|

I can change this if you can give us more info on which symbols should be permitted and which one not.

**Comment by lorthirk** [comment]
I already submitted a PR for this with #2246. Basically I'm using the [POSIX character class "Symbols"](https://www.regular-expressions.info/posixbrackets.html#class) in the REGEX now, instead of specifying single characters.

By the way, I think we're missing tests for the CredentialService implementation. I know you already provided one for the regex... we could update this one with the new characters, but we should also add some proper CredentialService test. Probably we should create an issue for that and address it in a later time, while we only fix the Regex test for now.
