### ISSUE TITLE
CRON Schedule Not In GMT

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2388]
If user enters start time at 00:00 and end time at 12:00 and CRON schedule for 0 0 12 * * ? (at 12:00 every day) Kapua returns an error. 
But this is not because of conflicting CRON/end time paramteres but because CRON schedule paramtere is somehow not in GMT. If user sets End Time for 13:00, all the parameters are accepted successfully. 
I think we should review how CRON schedule is checked in Kapua.

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Jobs, create a job (e.g. job0)
3. Select job0, go to its Schedule and try to create scheduel with following parameters:
 - name: sch0
 - starst on: today/00:00
 - ends on: today/12:00
 - CRON: 0 0 12 * * ?

**Expected behavior**
Either schdule with paramters 00:00/12:00/0 0 12 * * ? should be accepted or CRON scheudle should be reviewed. 

**Screenshot:**
![screenshot 2019-02-05 at 12 39 14](https://user-images.githubusercontent.com/15121999/52627451-a8f38280-2eb5-11e9-8811-895179ad7d99.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by Coduz** [comment]
Hi all, 

this is caused by the fact that CRON does not directly aware of the timezone. To avoid any problem with the server timezone (which is often depending on the underlying OS) I've set all CRON expression created to be based on UTC. 

The solution proposed by Aleksandra remove this forcing to UTC, but if (if I'm correct) make thing work only when the timezone of the browser is matching the timezone of the server, and would definitely not work with users from different timezones. 

i.e.:
User A creates a CRON with his timezone (+2:00 for example) like:
Starts: 10:00
End: 12:00
CRON: `0 0 12 * * ?`

User B views/edits the trigger from another timezone (+5:00 for example) and sees
Starts: 13:00
End: 15:00
CRON: `0 0 12 * * ?` <-- same problem, since CRON does not have any link to the timezone from which is created.

Moreover, if the trigger is created/retrieved/managed from the REST API we will not have any info about the User's timezone from the browser.

Let me know what you think.

As an alternative solution I would try to make clear that CRON is in UTC.

Regards,

_Alberto_

**Comment by ct-ajovanovic** [comment]
Hi @Coduz 
Yes, I can see how the changes from my PR would't be the correct solution for this issue.
About the alternative solution you proposed:

> As an alternative solution I would try to make clear that CRON is in UTC.


Do you mean to just add a text below the Cron schedule field?
 Something like _"The entered Cron Schedule must be in UTC" ?_
Make the user think in UTC instead of the local timezone?
Would that be the correct solution?
Regards,
_Aleksandra_

**Comment by Coduz** [comment]
Hi @ct-ajovanovic ,

Yes I think that making clear that the CRON must be expressed in UTC should be enough to avoid mistake. The actual issue is that is written nowhere and there is a clear lack of info about that. 

Whether to add a tooltip, or edit the label or add a small description under the field (like in the screenshot below) is up to you :) I'm fine with all of those solutions.

![Screen Shot 2019-04-24 at 11 04 04 AM](https://user-images.githubusercontent.com/3942036/56646890-c2b50100-6680-11e9-8505-4c76a9a549c9.png)

Regards, 

_Alberto_

**Comment by muros-ct** [comment]
I also have a considerations regarding scheduling.
It is dependent on where jobs are run from. Is it console module, or broker or api...
This is also dependent in which time zone is server with this services running, so in this case it is really hard to schedule job correctly.
How could this be changed, so it is run at actual UTC time?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
