### ISSUE TITLE
Scaling Kapua using Openshift

### ISSUE THREAD

**Issue by fedemonte89** [eclipse/kapua#2449]
Hi! I'm analyzing a possible architecture of  Kapua modules in a multi-node architecture using Openshift. Is it possible to install Kapua platform, for example, with multiple broker or multiple "api" module configuring a load balancer ahead of them?
What are Kapua limits?

Thank you for your response

**Comment by Coduz** [comment]
Hi @fedemonte89 ,

Currently non all components can be scaled without major changes.

Here is the breakdown by component.

**kapua/kapua-api**
It is stateless and can be scaled without issues, as far as we know

**kapua/kapua-console**
It it stateful, but if you ensure the session stickiness in the load balancer all will work normally. If not ensured there will be problems on the user session.

**kapua/kapua-broker**
This has the biggest problem, since the two nodes spawned will not 'synchronize' their status and the all functionalities regarding the Device Management are affected.
With some changes, this can be made work.

On this component @riccardomodanese can give you more information on problem/solutions.

If you need more clarifications, please ask.

Regards, 

_Alberto_

**Comment by fedemonte89** [comment]
Thank you @Coduz.
So I suppose that currently the only way to scaling on the client-side is to develop a new GUI using the kapua-api.

On the other hand, looking from devices prospective the kapua-broker could be a potential bottleneck. Right?

**Comment by riccardomodanese** [comment]
Hi @fedemonte89, on the broker side you can define a cluster and split the load between the brokers using a loadbalancer.
Kapua provides a static way to achive that (see: [activemq cluster](https://github.com/eclipse/kapua/blob/develop/assembly/broker/configurations/activemq.xml#L182)) so you need to configure your OpenShift environment in accordance with your nodes configuration.

Anyway the scaling factor depending on your requirements in term of message/subscription replication between the nodes.

**Comment by fedemonte89** [comment]
@riccardomodanese when you talk about the "broker", which part of kapua do you mean? "broker" or "events-broker" container?

**Comment by riccardomodanese** [comment]
Sorry with broker I mean the telemetry broker (so the "broker").
The "events-broker" should handle low load in a typically use.

**Comment by Coduz** [comment]
Hi @fedemonte89 ,

Any news on this?

Regards,

_Alberto_

**Comment by Coduz** [comment]
Hi @fedemonte89  ,

Closing this.
Feel free to reopen the issue if you need more help.

Regards, 

_Alberto_

**Comment by pintify** [comment]
> Hi @fedemonte89, on the broker side you can define a cluster and split the load between the brokers using a loadbalancer. Kapua provides a static way to achive that (see: [activemq cluster](https://github.com/eclipse/kapua/blob/develop/assembly/broker/configurations/activemq.xml#L182)) so you need to configure your OpenShift environment in accordance with your nodes configuration.
> 
> Anyway the scaling factor depending on your requirements in term of message/subscription replication between the nodes.

@riccardomodanese, could you update the reference to [activemq cluster](https://github.com/eclipse/kapua/blob/develop/assembly/broker/configurations/activemq.xml#L182)? I guess it referred [this](https://github.com/eclipse/kapua/blob/release-1.5.x/assembly/broker/configurations/activemq.xml#L185), but in the current develop branch I cannot find it, only somewhere in the tests

**Comment by riccardomodanese** [comment]
Hi, the configuration file is different since the broker has changed. I'll work on it.
