### ISSUE TITLE
How can i change database connect to my local MySQL

### ISSUE THREAD

**Issue by Xingxv** [eclipse/kapua#2641]
I want to store Kapua data to local MySQL.
How can i do?

**Comment by lorthirk** [comment]
Kapua currently uses Elasticsearch to store devices telemetry data, and H2 to store backend data. If you're talking about storing telemetry data in MySQL instead of using Elasticsearch, you need to write a different implementation for `kapua-datastore-api`. Otherwise, if you're looking to replace H2 with MySQL, you can provide all the configuration via system properties. You can see an example in [commons/src/main/resources/kapua-environment-setting.properties](https://github.com/eclipse/kapua/blob/1.0.5/commons/src/main/resources/kapua-environment-setting.properties)

Also, please use the [Kapua Gitter Room](https://gitter.im/eclipse/kapua) for Kapua related discussions. Thanks!
