### ISSUE TITLE
Expected Performance of broker (docker deployment)

### ISSUE THREAD

**Issue by lukas-bender-rodriguez** [eclipse/kapua#2655]
We see in our development deployment of Kapua a very poor performance of the broker. After we had connected about 15 simulated Kura-GW with Kapua, we had to find out that Kapua could not keep up with saving the data in the Elasticsearch database anymore. The load was about 7 messages per second.

Our deployment differs in certain ways from the deployment provided here. We use hosted elasticsearch instead of the container version, haproxy to terminate the mqtts connecton in front of the broker. 

Both the upscaling of elasticserch and the scaling of the virtual machine did not solve the performance problem. An analysis of the logs showed no particularities. 

Quite roughly, what is the expected performance of the docker deployment? How many connections and messages per second should be possible without problems? 
Where are the bottlenecks? ActiveMQ? Camel? the implementation of the elasticsearch datawriter?  

#644 related?

**Comment by riccardomodanese** [comment]
Hi, giving an answer is difficult without informations about docker servers sizing and messages structure (raw payload size and number and type of metrics contained).
Anyway I think @muros-ct can share performace test results to give you an idea about the overall system performance.

**Comment by lukas-bender-rodriguez** [comment]
The size of the messages differs but a typical message stored in elastic-search looks like:
```
{
  "_id": "d8b19e5f-66e8-4cc5-b25d-a93bfe17fb91",
  "_type": "message",
  "_index": "280524417925037204-2019-27",
  "device_id": "2445251573537930996",
  "channel_parts": [
    "B1",
    "gateway",
    "host_metrics",
    "signal",
    "raw"
  ],
  "scope_id": "280524417925037204",
  "channel": "B1/gateway/host_metrics/signal/raw",
  "received_on": "2019-07-06T08:47:28.072Z",
  "ip_address": "127.0.0.1",
  "metrics": {
    "CPU_Idle": {
      "flt": 9
    },
    "Swap_Total": {
      "flt": 104.8535
    },
    "RAM_Used": {
      "flt": 413.97043
    },
    "CPU_Temp": {
      "flt": 67.142
    },
    "DiskSpace_Total": {
      "flt": 7.7682033
    },
    "Swap_Percent": {
      "flt": 0
    },
    "DiskSpace_Percent": {
      "flt": 46.6
    },
    "Network_Packets_Sent": {
      "flt": 3.330793
    },
    "Network_Bytes_Sent": {
      "flt": 327.5235
    },
    "RAM_Percent": {
      "flt": 49.6
    },
    "assetTimestamp": {
      "lng": 1562402848049
    },
    "BootTime": {
      "flt": 26037504
    },
    "Swap_Free": {
      "flt": 104.8535
    },
    "RAM_Total": {
      "flt": 972.23474
    },
    "DiskSpace_Used": {
      "flt": 3.4508717
    },
    "CPU_User": {
      "flt": 22
    },
    "Swap_Used": {
      "flt": 0
    },
    "CPU_System": {
      "flt": 0
    },
    "RAM_Available": {
      "flt": 490.0946
    },
    "assetName": {
      "str": "host_metrics"
    },
    "DiskSpace_Free": {
      "flt": 3.950211
    },
    "Network_Packets_Recv": {
      "flt": 3.320719
    },
    "Network_Bytes_Recv": {
      "flt": 258.09958
    }
  },
  "sent_on": "2019-07-06T08:47:28.057Z",
  "body": null,
  "captured_on": "2019-07-06T08:47:28.057Z",
  "client_id": "Raspberry Pi 2",
  "timestamp": [
    1562402848057
  ]
}
```

The vm running the broker is a Standard_D4s_v3 (https://docs.microsoft.com/de-de/azure/virtual-machines/windows/sizes-general#dsv3-series-sup1sup) . It solely hosts the broker, api, event-broker and the console. The performance of elasticsearch looks good: 
![grafik](https://user-images.githubusercontent.com/42969040/61289621-03c53900-a7ca-11e9-967b-38ecc10044dc.png)

**Comment by LeoNerdoG** [comment]
Hi @lukas-bender-rodriguez,
I will answer on behalf of Uros who is not on the proejct any more. 
Bellow you will find the test results that we have from some time ago (15th April 2019). 

Types of requests that are being sent:

•	HTTP Request – Used for counting messages that are being sent
•	MQTT Request  (BIRTH) – Message for creating device
•	MQTT Request – Metrics sent from device
•	MQTT Request (DC) – Message for destroying device

Graphs that are being used:

•	Server hits per seconds - This graph will display the hits generated by devices to Kapua per second. It will show us how much maximum load can Kapua take.
•	Response latencies over time – This graph will display the response latencies during the load test showing us how much time will it take for Kapua to respond to requests.

We have 3 types of tests: 
 - Minimal load test (twenty devices, 100 messages per device)
 - Test with more devices but less messages (1000 devices, 10 messages per device)
 - Test with less devices but more messages (10 devices, 1000 messages per device)


1. Minimal load test (20 devices, 100 messages per device):

**Server hits/second:**
![image](https://user-images.githubusercontent.com/15121999/61460786-c26e8e00-a96f-11e9-821a-0410366aeea4.png)

**Response latencies over time:**
![image](https://user-images.githubusercontent.com/15121999/61460823-d4e8c780-a96f-11e9-9645-f328684c0c21.png)

**Aggregated report:** 
![image](https://user-images.githubusercontent.com/15121999/61460848-ddd99900-a96f-11e9-840a-6d588f2398d4.png)



2. Test with more devices but less messages (1000 devices, 10 messages/device):

**Server hits/second:**
![image](https://user-images.githubusercontent.com/15121999/61460953-14171880-a970-11e9-8147-2d90e2c2e5a7.png)

**Response latencies over time:**
![image](https://user-images.githubusercontent.com/15121999/61460978-1b3e2680-a970-11e9-82be-0c766e1571cf.png)

**Aggregated report:** 
![image](https://user-images.githubusercontent.com/15121999/61460997-24c78e80-a970-11e9-8c39-7f753e4b26f6.png)



3. Test with less devices but more messages (10 devices, 1000 messages/device):

**Server hits/second:**
![image](https://user-images.githubusercontent.com/15121999/61461041-3c9f1280-a970-11e9-8d53-41dcb6565a56.png)

**Response latencies over time:**
![image](https://user-images.githubusercontent.com/15121999/61461052-43c62080-a970-11e9-99c6-ff6526d96964.png)

**Aggregated report:** 
![image](https://user-images.githubusercontent.com/15121999/61461074-4b85c500-a970-11e9-95dc-f129ad60aaa9.png)


It may be possible that performances have dropped since a lot of new code has been introduced but we would have to run the tests again to be sure. I will have to conduct some more tests on my side, to see the current performances. 
Are you using the latest develop branch or any other branch with some custom changes maybe?
Do you need any more assistance from my side regarding this?

**Comment by muros-ct** [comment]
Tnx @LeoNerdoG for sharing report. But! We have to be careful about these results, this is really basic test and environment was not set up completely as it should be. I think results could be even better if test environment would be set up completely independently.
Also network issues were not taken into consideration during this test.

If anyone is interested in testing MQTT on Kura, I recomend you to take a look at my custom plugin for JMeter at https://github.com/muros-ct/jmeter
Just clone and build JMeter. Then if you need test examples, @muros-ct  or @LeoNerdoG  can provide you with test scenarios for JMeter.

I also published two screen recordings while testing Kura MQTT. I was using JMeter on dockerized environment that is also available on dockerhub.

https://www.youtube.com/playlist?list=PL9se1QsZWBnU0ZQxfx6VeBdqb23qvze49

Dockerhub images:
https://cloud.docker.com/u/murosct/repository/docker/murosct/jmeter-client
https://cloud.docker.com/repository/docker/murosct/jmeter-server

Hope this helps. 
If you need further help, do not hesitate to contact me or @LeoNerdoG, we will be glad to help you.

**Comment by riccardomodanese** [comment]
Hi, I did a test using an AWS machine (m5.xlarge - 4 cores - 16GB) and I didn't notice any performance issue with a load comparable with yours.

Test machine:
	m5.xlarge - 16GB - 4cores
	Centos based AMI
	OpenJDK 1.8
	Docker 1.13.1

Remote clients:
        20 clients
        publishing rate 150ms (aggregated messages rate around 130msg/s)
        20 metrics/message

Kapua
	latest develop (based on latest commit available on develop branch)
	NO configuration or code changes

Run Kapua via docker-compose (using docker-deploy.sh script)

I compared published messages count with those available in ES (curl -s machine-ip:9200/1-2019-30/message/_count) and after a ramp up of few thousand messages (ES is empty so Kapua needs a while to initialize schemas and indexes) the counters are aligned.

**Comment by Coduz** [comment]
Hi @lukas-bender-rodriguez ,

do you have any other question on this topic? 

Regards, 

_Alberto_

**Comment by ghost** [comment]
Sorry for the late reply and thanks for the helpful feedback. However, we decided to use a dedicated mqtt broker to handle telemetry data and to use the kapua broker for the device management solely.

In our specif use case this seems appropriate because a simple mqtt broker is sufficient for us and we don't use the additional possibilities of ActiveMQ and Camel.

**Comment by Coduz** [comment]
Hi @lukas-bender-rodriguez ,

Good.
I'll close the issue then.

Regards ,

_Alberto_
