### ISSUE TITLE
Problem with endpoint_info permission on Back-End side

### ISSUE THREAD

**Issue by ct-anaalbic** [eclipse/kapua#2677]
**Describe the bug**
On GUI side, if user which not have `endpoint_info` permission try to find endpoint without account permission, it will not work. Also if the same user try to edit or delete endpoint in every case it won't be possible. But in tests, scenario like this is passed. 

**To Reproduce**
1. Login as kapua-sys or any other user that has proper permissions
2. Create user _user1_
3. Create role _role1_
4. Create endpoint _endpoint1_
3. Create permission with domain endpoint_info, and add permission to the role _role1_
4. Add _role1_ to the user _user1_
5. Logout
6. Login as user _user1_
7. Try to find, edit or delete endpoint _endpoint1_

**Expected behavior**
This scenario can not be reproduced on GUI side (if user has account permission he can see endopoint in settings tab, but can't add or delete endpoint). In Cucumber test scenarios, this is possible.

**Screenshots**
_Screenshot1_ (GUI - User has account and endpoint permissions and he can see endpoint - _deployment info_, but can't add new one, or delete and edit existing endpoint)
![image](https://user-images.githubusercontent.com/45655642/62784925-d1a0b180-babf-11e9-8465-df52aebe4f88.png)

Screenshot2 (Cucumber Test Scenario - find, edit and delete endpoint steps passed when user has only endpoint_info permission)
![image](https://user-images.githubusercontent.com/45655642/62784994-f5fc8e00-babf-11e9-8bdc-ad5653c8a02a.png)

**Version of Kapua**
_develop_ Kapua

**Type of deployment**
[ ] Local Vagrant deployment
[ ] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Additional context**
I am not sure but is this really a issue?

**Comment by Coduz** [comment]
Hi @ct-anaalbic ,

Uhmmm it seems like a corner case. All you said is true. 
But this is due to the fact that the `Settings` view is reserved to user with `account:view` permission.

A strange thing is that the `user1` is able to edit and delete since permission required to perform those actions are:
update: [AUTHORIZATION_SERVICE.checkPermission(PERMISSION_FACTORY.newPermission(EndpointInfoDomains.ENDPOINT_INFO_DOMAIN, Actions.write, null));](https://github.com/eclipse/kapua/blob/develop/service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointInfoServiceImpl.java#L123)

delete:
[AUTHORIZATION_SERVICE.checkPermission(PERMISSION_FACTORY.newPermission(EndpointInfoDomains.ENDPOINT_INFO_DOMAIN, Actions.delete, null));
](https://github.com/eclipse/kapua/blob/develop/service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointInfoServiceImpl.java#L146)

So both require admin access or at least a permission like `endpoint_info:*:*`

I can see that the permission on the test are created with the `scopeId` but not the `targetScopeId`. 
This likely means that permission assigned to that role are:
`endpoint_info:read:*`
`endpoint_info:write:*`
`endpoint_info:delete:*`

Could you please check? 

Regards, 

_Alberto_

**Comment by ct-anaalbic** [comment]
Hi @Coduz,

Yes, I will check this. 

Regards, 
_Ana_

**Comment by ct-anaalbic** [comment]
Hi @Coduz,

I checked this. If role permissions are created with `scopeId`, than permissions which are assigned to role are with domain `endpoint_info`, and with actions `read`, `write` and `delete`. But It is defined in test scenario. If i create permissions with  `targetScopeId`, than an illegal value is forwarded for `scopeId` and scenario is failed. 

But can the user modify or add endpoints in any case? On GUI user is not able to work completely with endpoints. User only can see endpoints if has permissions with `endpoint_info` and `account` domain, but adding or deleting endpoints is disabled in every case. In test scenario all actions with endpoints have passed only with `endpoint_info` permission (adding endpoint, deleting endpoint and so on).

Regards,

_Ana_

**Comment by ct-anaalbic** [comment]
I just tried to delete or edit endpoint with user which has _endpoint_info_ permissions created with `targetScopeId`. On this way, only searching for endpoints are enabled. Other actions, like editing or adding endpoints are not allowed. Maybe this is the solution?

Regards,

_Ana_

**Comment by Coduz** [comment]
Hi @ct-anaalbic ,

Sorry for the long awaiting.

The endpoint can be only edited by `kapua-sys`. This is because the host name usually must match a DNS record or a specific IP of the deployment.
So this is something that a regular user should not be able to manage.

Instead this info must be available to all user since they are meant to be of public domain to know which is the broke URL for example.

Regards, 

_Alberto_

**Comment by ct-anaalbic** [comment]
I closed this because issue is resolved.
