### ISSUE TITLE
Do we really need ConnectorDescriptor?

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kapua#314]
Why do we really need ConnectorDescriptor [1] and ConnectorDescriptorLoader [2] classes? Apparently those are used only to provide information about connection type, but are specified statically aka hard-coded. That would mean that anybody willing to use new transport in ActiveMQ has to add this hard-coded information into core ConnectorDescriptorLoader.

Do we really need those definitions? I would propose just to copy information about connector type into message header and NOT to register possibile types anywhere in the code.

What do you think?

[1] https://github.com/eclipse/kapua/blob/5fbbca64359dd2042bbc7c058cd4b1cf3a2e54d1/broker-core/src/main/java/org/eclipse/kapua/broker/core/plugin/ConnectorDescriptor.java
[2] https://github.com/eclipse/kapua/blob/f6bb22040ce2cc08238f993d878a6e38b34ea9ef/broker-core/src/main/java/org/eclipse/kapua/broker/core/plugin/ConnectorDescriptorLoader.java

**Comment by riccardomodanese** [comment]
Hi Henrik, 
I try to explain briefly how the ConnectorDescriptor works, that may help to understand why this code was wrote.
The connector descriptor was introduced to help the broker to translate messages from the transport layer(1) to the Kapua layer(3) through the application layer(2).
The implementation configurability (by configuration files) of the current connector description was expected but it's still work in progress.
Every device connected has a specific couple of protocols (I mean transport (mqtt, jms) and application (kura, others?)), so the Kapua layer MUST have information about how to convert the message coming from the transport layer(1) to the application layer(2) to Kapua layer(3).
We have no insurance that a device can tell to Kapua which application protocol is using (since Kapua should interoperate with different already existing protocols we can't force a device to do that), so we hard-bind an application protocol to an external transport connector.
In few words, we are handling a n-m protocols matrix in a plain way.
If we have 2 kinds of devices that use the same transport protocol (mqtt) but with 2 different application protocol (Kura and another) we should define 2 different mqtt connectors on the broker side. In that way Kapua is able to correctly translate the messages received by the 2 kinds of clients.

In any case I think it's better to discuss about that in the incoming scrum.

**Comment by ctron** [comment]
So it would be a good idea to make this configurable, providing some reasonable defaults. And get rid of the hard-coded stuff.

**Comment by ctron** [comment]
I think we can close it, any objections?

**Comment by riccardomodanese** [comment]
I agree, we can close it
