### ISSUE TITLE
kapua-console website empty body

### ISSUE THREAD

**Issue by liaoweiguo** [eclipse/kapua#468]
here is the log:
633221 [qtp1945604815-51] ERROR o.e.k.a.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /Kapua.nocache.js - Error: Not Found 
633282 [qtp1945604815-49] ERROR o.e.k.a.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /console/skin/skin.css - Error: Not Found 
633283 [qtp1945604815-20] ERROR o.e.k.a.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /console/skin/skin.js - Error: Not Found 

is there any way to fix this, the old version works

**Comment by ctron** [comment]
Have you cleaned and rebuild the whole project? Which way are you running the console? OpenShift, docker, vagrant, native jetty maven plugin,...?

**Comment by liaoweiguo** [comment]
I donot build, just pull the docker images

**Comment by ctron** [comment]
Which one?

**Comment by liaoweiguo** [comment]
kapua-console-jetty

docker run -td --name kapua-console --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8080:8080 kapua/kapua-console-jetty

**Comment by liaoweiguo** [comment]
is there comments about build & run the project locally, I builded docker images, but `dock run` still use remote images

buile images:

```
mvn -Pdocker
mvn -Pdocker-push
```

run
```
docker run -td --name kapua-sql -p 8181:8181 -p 3306:3306 kapua/kapua-sql
docker run -td --name kapua-elasticsearch -p 9200:9200 -p 9300:9300 elasticsearch:2.4 -Dcluster.name=kapua-datastore -Ddiscovery.zen.minimum_master_nodes=1
docker run -td --name kapua-broker --link kapua-sql:db --link kapua-elasticsearch:es -p 1883:1883 -p 61614:61614 kapua/kapua-broker
docker run -td --name kapua-console --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8080:8080 kapua/kapua-console-jetty
docker run -td --name kapua-api --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8081:8080 kapua/kapua-api-jetty

```

the docker run command complain no local image and pulling from lib
`Unable to find image 'kapua/kapua-XXXX:latest' locally`

thanks

**Comment by lorthirk** [comment]
@liaoweiguo,

When running `mvn -Pdocker` can you see Docker images generating in the log? They sould be building in the `kapua-assembly` project

**Comment by ctron** [comment]
I can replicate the issue locally. I will check into this.

**Comment by GogicM** [comment]
Hello, 
I have same problem. When I installed kapua with docker on windows and run it with Kitematic, all works well. 
But when I run it from terminal, I have same errors.
mvn -Pdocker generates images in the log.
Regards,
Milan

**Comment by ctron** [comment]
Currently it looks to me like as if the CI system generating the Docker images created a half-empty WAR file, which then gets used to build the docker image. When I build locally however this seems to work fine.

**Comment by ctron** [comment]
I spotted a difference, enabling the profile `dev` makes the difference between a half-empty and a working WAR file.

**Comment by ctron** [comment]
Ok the difference is that `KapuaDev.gwt.xml` renames the output to `Kapua` while `Kapua.gwt.xml` does not rename anymore. However GWT modules are generated by their full package name.

**Comment by GogicM** [comment]
Hm...
On windows / local : http://prntscr.com/exrq3r
With terminal, on server: http://prntscr.com/exrqop

**Comment by ctron** [comment]
I just pushed a commit. This should fix the issue. For the docker images on DockerHub this will take around 45 minutes to get updated, but you should be able to pull the changes from git and build it locally.

**Comment by ctron** [comment]
@GogicM It looks to me as if you didn't update the docker images on your local machine. Which may be fine for the next 45 minutes 😉  Because this shows the old content. You will probably do something like "docker pull" in order to get a freshly pulled image. However I would suggest to wait until the docker images are updated. I will let you know once this works for me.

**Comment by ctron** [comment]
Docker images are pushed an I can validate that it is fixed for me.

**Comment by liaoweiguo** [comment]
Great it works for me

**Comment by ctron** [comment]
Cool thanks!

**Comment by rougeo** [comment]
Hello sorry to re-open this again but i have some issues. I am using the docker images to run kapua as described  But if i run :

1 - mvn -Pdocker ; i have message at the end (after all the downloading stuff)

![screen shot 04-20-17 at 03 03 pm](https://cloud.githubusercontent.com/assets/12080962/25237262/6dcfb226-25ea-11e7-8efd-bd2301eb4e2a.PNG)

2- mvn -Pdocker-push : i have this message too

![screen shot 04-20-17 at 04 15 pm](https://cloud.githubusercontent.com/assets/12080962/25237341/a8d05b5a-25ea-11e7-9a4f-158d85302b0f.PNG)



Then if i run the 5 docker run command, kapua works almost fine with just the setting part wich is disabled !

![screen shot 04-20-17 at 04 39 pm](https://cloud.githubusercontent.com/assets/12080962/25237406/e1660f1e-25ea-11e7-9a58-8064254c0337.PNG)


I don't know if these error matters but i wouldlike to be sure. And about the disabled settings ????

**Comment by ctron** [comment]
This seems like a problem you have with the unit tests in the datastore implementation. Running `-Pdocker` on the full build.

If you run the build (with `-Pdocker`) in the `assembly` folder then only the docker images will get re-generated. That may help sometimes.

As the datastore unit tests are failing frequently, I would suggest do disable those for the moment with `-DskipTests`.

If you have other issues, please open a new bug for each of them.

**Comment by lorthirk** [comment]
The settings are disabled because you're only supposed to view your own settings, while you can edit settings on child accounts; so this is actually not an issue.

About the failed builds, could you provide some detailed logs in order to check exactly what tests are failing and hopefully why?

**Comment by rougeo** [comment]
Hello !! the mvn -Pdocker  is now working fine from the assembly folder !! thanks

I have just others issues on the device management part, but like ctron said, i'll open other bugs for that.

**Comment by rougeo** [comment]
Hello !! Again about the empty website !! 
- The mvn -Pdocker is working fine (no error at all) and all the docker images are downloaded

-The mvn -Pdocker-push shows me this 
![screen shot 04-25-17 at 11 19 am](https://cloud.githubusercontent.com/assets/12080962/25378617/da6a12aa-29aa-11e7-8721-0ab6433b4fc5.PNG)

I think it because i have not right to push !! (I don't think that i really need this command anyway)


Then if i run : 
`docker run -td --name kapua-sql -p 8181:8181 -p 3306:3306 kapua/kapua-sql

docker run -td --name kapua-elasticsearch -p 9200:9200 -p 9300:9300 elasticsearch:2.4 -Dcluster.name=kapua-datastore -Ddiscovery.zen.minimum_master_nodes=1

docker run -td --name kapua-broker --link kapua-sql:db --link kapua-elasticsearch:es -p 1883:1883 -p 61614:61614 kapua/kapua-broker

docker run -td --name kapua-console --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8080:8080 kapua/kapua-console-jetty

docker run -td --name kapua-api --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8081:8080 kapua/kapua-api-jetty`

the http://localhost:8080 remain empty and we have this log !!
![screen shot 04-25-17 at 11 27 am](https://cloud.githubusercontent.com/assets/12080962/25378784/5cde7122-29ab-11e7-82e4-15246b0d36c7.PNG)

Yet if i  try update the docker images with the (docker pull), the images is updated (it looks like we have not the latest docker image with the  mvn -Pdocker command).  And then whith the run  command, the website isn't empty.  Some ideas ? the thing is i wouldlike to apply the new "develop" update to my running containers, beacuse for instance  @lorthirk  fixed the "Added Device Event export implementation #508" but it still not working for me. 
Thanks !!
PS: I already did a git pull and saw the updates.

**Comment by ctron** [comment]
You cannot push to docker under the account `kapua`. Please see section [pushing](https://github.com/eclipse/kapua/tree/develop/assembly#pushing), it explains how to build and push under a different (your) account.

Of course, if you want to use docker images from another account, you will need to modify the `docker run` commands to reflect that change and specify which account to use: e.g. `docker run … youraccount/kapua-sql`

**Comment by rougeo** [comment]
That what i am trying to do now !! thanks !! 
But using the simple "mvn -Pdocker" then running the docker run .... command is showing an empty page. 


Yet if i pull from your repos the latest images, then i run the "docker run command" it is working.  I don't understand why. (it's like  the  mvn -Pdocker is not downloading the latest images ).

**Comment by ctron** [comment]
`mvn -Pdocker` is not downloading, but locally building the new docker images. It does that under the name `kapua/xxx`. For this it is using the locally compiled versions of the JARs and WARs.

It may be that you did a `mvn install` with the wrong version (of the web console e.g.) which would result in the wrong WAR to be packaged into your local docker image, unless you rebuilt and installed (`mvn clean install`) the kapua top-level project afterwards. Thus starting up the new docker image would also contain the old stuff.

If may also be that (due to some other reason) the docker images did not get refreshed. You should be able to check this with:

```bash
$ docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
kapua/kapua-api-jetty                 latest              83940623d4f4        5 seconds ago       200.1 MB
kapua/kapua-api                       0.2.0-SNAPSHOT      a29788f898a4        10 seconds ago      244.5 MB
kapua/kapua-api                       2017-04-25          a29788f898a4        10 seconds ago      244.5 MB
kapua/kapua-api                       latest              a29788f898a4        10 seconds ago      244.5 MB
kapua/kapua-console-jetty             0.2.0-SNAPSHOT      fb7e2544e02f        17 seconds ago      248 MB
kapua/kapua-console-jetty             2017-04-25          fb7e2544e02f        17 seconds ago      248 MB
kapua/kapua-console-jetty             latest              fb7e2544e02f        17 seconds ago      248 MB
kapua/kapua-console                   0.2.0-SNAPSHOT      126681bd4568        26 seconds ago      284.2 MB
kapua/kapua-console                   2017-04-25          126681bd4568        26 seconds ago      284.2 MB
kapua/kapua-console                   latest              126681bd4568        26 seconds ago      284.2 MB
kapua/kapua-broker                    0.2.0-SNAPSHOT      b3809e8a0b05        33 seconds ago      228.1 MB
kapua/kapua-broker                    2017-04-25          b3809e8a0b05        33 seconds ago      228.1 MB
kapua/kapua-broker                    latest              b3809e8a0b05        33 seconds ago      228.1 MB
…
```

If the dates under "CREATED" or actually older than a few seconds after the build. Then your local docker images are stale and did not get updated. If you are starting with the default images names, the prefix must be `kapua/`.

**Comment by rougeo** [comment]
I understand now !! Actually i thought that the images were downloaded from the ducker hub first, but it is a local build !! Thank you !!! Now i understand how it really work.

To be sure i have deleted the kapua folder !! cloned the repo again and run "ONLY" the "mvn -Pdocker" command  in the assembly folder . The docker images are actually well builded and only the elasticSearch is pulled from the docker hub. But i still have the empty web console if i run theses images. Here the logs
![screen shot 04-25-17 at 03 55 pm](https://cloud.githubusercontent.com/assets/12080962/25389129/0d583546-29d0-11e7-9a8a-0e5e03ac9506.PNG)

> `37612 [qtp1945604815-19] ERROR o.e.k.a.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /Kapua.nocache.js - Error: Not Found
37656 [qtp1945604815-13] ERROR o.e.k.a.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /console/skin/skin.js - Error: Not Found
37656 [qtp1945604815-33] ERROR o.e.k.a.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /console/skin/skin.css - Error: Not Found
`

**Comment by ctron** [comment]
As I tried to explain, you MUST build the full project. Not only the assembly module. Otherwise you will have stale artifacts in your local Maven repository.

**Comment by rougeo** [comment]
Hello thank you !! Now it working fine, the local images are builded well. Actually i was stuck with the "mvn clean install" command whitch is not working. I finnally found the command "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V " on  [your travis CI](https://travis-ci.org/eclipse/kapua/jobs/225666638) g.  

Thanks !! Awsom job guys !! Hope that you'll put a feature to upload or delete  package for a group of kura devices in one actions.
:+1:
