### ISSUE TITLE
The Data View in the console get stuck when there are no messages stored

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#477]
* Start a Kapua instance with an empty datastore (for example create a brand new instance with no devices connected to it).
* Click on "Data" to open the data view.

The "Available Topics" panel is stuck and a popup appears giving the feeling that something is going to be loaded. Shortly an error popup message appears in the lower right corner of the UI notifiying that there are no indexes in the datastore (which is the truth).

The error should be managed more kindly and the user should be adviced that there are no data available.

**Comment by lorthirk** [comment]
While this is technically closed by 99ac29adc192db400f00191d65cf62d25a573062, this implementation has two drawbacks:

- Datastore shouldn't fail anyway when there's no data, so that error should be fixed in the Datastore implementation
- This will show the same message for any kind of Datastore issue, which can be misleading if the error is actually different.

I'll close this one, but I suggest to open a new issue to avoid losing track of this.
