### ISSUE TITLE
KapuaConfigurableService does not implement KapuaService

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#489]
The `KapuaConfigurableService`does not implement `KapuaService`. However that is a requirement for the `KapuaServiceLoader`.

Which is circumvented in `org.eclipse.kapua.app.console.server.GwtAccountServiceImpl.updateComponentConfiguration(GwtXSRFToken, String, String, GwtConfigComponent)` by using raw classes.

I think that either the requirement that classes must extend `KapuaService` should be dropped or `KapuaConfigurableService` must extend `KapuaService`.

**Comment by Coduz** [comment]
Hi @ctron ,

`KapuaConfigurableService` does not need to extend from `KapuaService` because an entity service (e.g. `AccountService`) will extend from `KapuaService` to enable service location, and will also extends `KapuaConfigurableService` to enable service configuration per scope. 

In the specific case this is an error I believe and the code can be also written in this way: 
```
KapuaLocator locator = KapuaLocator.getInstance();
AccountService configurableService =  locator.getService(AccountService.class);

// execute the update
Map<String, Object> parameters = GwtKapuaModelConverter.convert(configComponent);

configurableService.setConfigValues(kapuaScopeId, kapuaParentId, parameters);
```

I will discuss with @lorthirk  to know if there is any reason for that and also if that method is still needed.

Regards, 

_Alberto_

**Comment by lorthirk** [comment]
@Coduz your change totally makes sense to me. Probably it has been copy/pasted from somewhere else during the branch development and then survived in the commit.

Also, as you said, that method is probably not even used anymore. Let's investigate that a little, but I suspect it can be removed.

**Comment by ctron** [comment]
I created a PR for this, maybe you can have a look at this.
