### ISSUE TITLE
Split up 'assembly' project in different sub-modules for docker containers

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#529]
I would like to split up the `assembly` project into different sub-modules, each for the different docker container, having a common `docker` base parent.

This should solve issue #518 which seems to originate from Maven's inability to aggregate the complex configuration structures of the docker maven plugin. Creating single maven projects should reduce this complexity a lot.

**Comment by hekonsek** [comment]
Should I start to work on this now or wait for the release? I don't want to mess with the project structure if we are in the middle of the release process.

**Comment by ctron** [comment]
I think we still have an issue with the tagging. So maybe fixing this for the release would be better.

**Comment by hekonsek** [comment]
Noted :) .

**Comment by hekonsek** [comment]
@ctron It seems that I cannot create Docker images from binaries generated in `assembly` module and least not without copy-pasting assembly configuration into Docker modules. The solution for that would be to move creation of assembly binaries from monolithic `assembly` into dedicated modules as well. So maybe instead of having single assembly and dedicated docker modules, we will just split `assembly` into submodules? Each module could contain assembly plus Docker configuration for given artifact (broker, console, etc).

What do you think?

**Comment by ctron** [comment]
Sounds like a plan!

If we want to re-use those assemblies for other purposes, I think we should assemble the anyway in a differently (including proper license files, different prefix path, etc). We could do that, but also in this case we should split up the assembly module into different "assembly-broker, assembly-…" projects, declare them as attached primary artifact and upload them to maven central (when deploying). I guess in this case the docker image sub-modules could declare a dependency on the assembly, correct?

But for the moment, I would say simply splitting this up into single sub-modules is fine!

**Comment by hekonsek** [comment]
Done.
