### ISSUE TITLE
Resource limit check in configurable services should manage non fixed set of properties

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#558]
Currently the implementation can manage only:

* infiniteChildEntities
* maxNumberChildEntities

**Comment by lorthirk** [comment]
I'm going to close this issue right now, because any service implementation can manage whatever property, not just the one described in this issue. Those two are just the standard properties that are checked by `AbstractKapuaConfigurableResourceLimitedService` for resources limiting, but the actual services can extend this and manager whatever property they need.
