### ISSUE TITLE
Wrong Timestamp format on Data View

### ISSUE THREAD

**Issue by lorthirk** [eclipse/kapua#621]
It seems that currently the messages timestamp in the Data view is wrong:

<img width="306" alt="timestamp_wrong" src="https://cloud.githubusercontent.com/assets/8140139/26633762/bde67ea8-4614-11e7-9b74-86851cfa8861.png">

While it should be:

<img width="215" alt="schermata 2017-06-01 alle 10 10 20" src="https://cloud.githubusercontent.com/assets/8140139/26670603/8bd3d99e-46b2-11e7-9fd5-13fbd95e4abc.png">

**Comment by ctron** [comment]
To honest ... I would prefer the full timestamp. "Today" is relative and this not really helpful if you don't have the full context.

**Comment by lorthirk** [comment]
I get your point. I opened this issue because the Data view wasn't coherent with all the other dates currently shown in the console. We could think of make all the dates absolute in the console, or we could have only this timestamp as an absolute date. What do you think?

**Comment by ctron** [comment]
So perfect option would be: let the user decide 😉 

Otherwise I would opt for "all absolute"

**Comment by lorthirk** [comment]
I'd say to go with the full date everywhere as of now, and think about improving it letting the user decide in the future

**Comment by Coduz** [comment]
User setting would be tricky and long because you'll have also to create user preference panel and have a store on the console in which store this info. 

I think that ISO 8601 with timezone :) ie `2017-06-01T11:44:30+02:00`

**Comment by ctron** [comment]
I didn't say to this right away. But showing timestamps like this can be quite tricky in such a system. Which timezone is it? The browser? The server? The source? Using relative timestamps would make this even worse.

I would opt for UTC and simply stating that in the column header. Adding timezone support at a later time.

**Comment by Coduz** [comment]
The timezone has been managed by the code automatically since now and it has always worked as far as I know :) 
And is it something that is done also on AWS console and many other web application that uses timezone on output. 
I don't think that it would be a problem :) 
So:

- Server: UTC 
- Source: sens messages in UTC timestamp
- Display via WEB console: timezone specific, handled by the client code on the browser side. Server will not know anything about that

**Comment by lorthirk** [comment]
#623 has been updated to use ISO8601 format and UTC timezone in all views

**Comment by ctron** [comment]
So of course the timezone should be UTC. The most simple way in Java.

But just assume your device is located in California, while your server is in Europe and your user is in Tokio.

Which timezone should the user see? A peak of some metric around 4am JST might seem completely strange, while it seems quite normal around 12:00 PDT. Still is always is 19:00 UTC.

**Comment by Coduz** [comment]
Use the timezone from the device location is impossible because the device (Kura) uses long millis in UTC we can't track the timezone in which the device comes from. 
So _device_ to _server_ is UTC. 

Server stores all in UTC obviously.

Data is sent to the browser in UTC and then, based on the browser locale that the user has. If the user comes from Italy it will have CET/CEST timezone. From Japan il will be JST. 

I think that we all agree on this.

What me and @lorthirk have some problem understanding your position.
We already have timezone support, not configurable, based on the browser settings.

You want to use all UTC and then make configurable the timezone at later time or having timezone support not configurable is ok for you?

**Comment by ctron** [comment]
I don't think we will solve this for 0.2.0, but in general: assume that you have a system with devices and users distributed all over the world. Looking at some device data without timezone information is confusing as users and devices could be in different time zones. So I fully agree with using UTC for transmitting, recording timestamps, please don't use anything else than UTC!

But for showing data UTC or the user's local timezone may not be good enough. It may be important to know the timezone of the device. I know the Kura has a bunch of limitations, but maybe we need a fix there too.

So again, consider a device sitting in north america and two users sitting in europe and japan, looking at the same timestamp. Both will see a different timestamp and still the timestamp is out of context, as the device is again in its own timezone.

Assume some peak at lunch time, this looking at this in a different timezone than the device is, may offset that peek during the night or at some other time. Letting it make no sense at all. However if you would show timestamps in the timezone of the device (including the zone information) it might very well make sense.

**Comment by Coduz** [comment]
You can improve Kura as much as you want, but you cannot ensure that each publishing has a position to determine the timezone. You can cover static devices by having a setting, but for moving devices you can't.

I think that having the timezone of the device would be nice to have, but impossible to have it as a pre-requisite to publish data.

**Comment by lorthirk** [comment]
Discussions will continue in #631 after this issue will be closed when #623 is merged
