### ISSUE TITLE
Unable to edit permissions of child account users

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#664]
Currently it is not possible to use the Web UI to edit the permissions of child account users.

Child account users do not appear on the normal "users" view, but only in the "users" tab of the "child accounts" details pane. However this tab does not allow to edit the child accounts users permissions.

**Comment by stefanomorson** [comment]
The "users" view shows the users who belong to the current account.  In order to grant the permissions to the users of a child account you have to switch from the current account to the child account. You do that from the user menu on the top right corner of the U (Menu -> Switch to account ...) the menu will give you access to all your child accounts.
Once you are in the child account the "users" view will show the list of its users and you can edit they're roles and permissions.

**Comment by stefanomorson** [comment]
I think the last comment answers the question so I'm going to close this issue.
If there are feedback or more questions feel free to reopen it if.
