### ISSUE TITLE
streams

### ISSUE THREAD

**Issue by zhouyue123** [eclipse/kapua#782]
how to use streams API ?

**Comment by lorthirk** [comment]
You can find Swagger UI documentation at `http://localhost:8081/doc` if you use Docker deployment. Currently Streams API only supports publishing a data message to a topic, not subscribing to topics.

**Comment by zhouyue123** [comment]
when i  input the parameter  
![image](https://user-images.githubusercontent.com/28722594/29704593-107637a4-89ad-11e7-81e0-50be1836cc52.png) and Parameter content type is  application/json  ,server response 500,error message:
![image](https://user-images.githubusercontent.com/28722594/29704668-5f10bc68-89ad-11e7-8fc5-0a79c4312bf1.png) , this is parameter type wrong?

**Comment by lorthirk** [comment]
So, here's the payload I use to test the Publish REST API:

```
{
  "type": "kapuaDataMessage",
  "position": {
    "type": "kapuaPosition",
    "latitude": 0,
    "longitude": 0
  },
  "clientId": "client-id-here",
  "channel": {
    "type": "kapuaDataChannel",
    "semanticParts": ["test", "test2"]
  },
  "payload": {
    "type": "kapuaDataPayload",
    "metrics": [
      { 
        "valueType": "string",
        "value": "ls",
        "name": "command.command"
      },
      {
        "valueType": "string",
        "value": "-lisa",
        "name": "command.argument0"
      }
    ]
  },
  "deviceId": "Jr73FZ8fbSQ",
  "clientId": "my-client-id",
}
```
As you can see, the model is quite different from the one the Swagger generates:
- The `scopeId` and the `id` fields are missing because they are actually model fields but they are automatically generated after Kapua receives the message; even if you specify them they would be overridden by the ones that Kapua generates
- The `deviceId` format must be in the short Base64 format, which is the one used everywhere in the REST APIs to serialize `KapuaId` entities
- You need to specify the exact interface for the various objects you create, and in my example this is done with the `type` property in every complex object

I took a note to improve the SwaggerUI model generation according to this note. If you have any further question feel free to ask!

**Comment by stefanomorson** [comment]
Hi,

since both #783 and #786 are closed and there's no new feedback, can this issue be closed ?

@lorthirk if necessary we may create a separated issue for improving the API documentation in Swagger UI.

**Comment by stefanomorson** [comment]
Close the issue for inactivity.
If new feedbacks and questions will come feel free to open it up again.
