### ISSUE TITLE
Kapua - Update on multiple devices

### ISSUE THREAD

**Issue by RaghAkella** [eclipse/kapua#836]
Hi,

I am currently exploring kapua and have multiple questions,

1. Now in Kapua Devices option we can select a device (OSGI Container running) and able to perform an operation like stop/start bundle. Do we have an option like performing same operation on multiple devices(Kind of bulk update) instead of selecting a device and updating it every time.

2. Do we have Rules Engine concept in kapua?

3. I am new to data analytics and kapua also. Here my question is, how could we integrate Data analytic and visualization in kapua. I have read using elasticsearch + spark+ kibana we can do real time data analytics. Can we integrate spark into kapua?

Please help me.

Thanks,
Raghav

**Comment by Coduz** [comment]
Hi @RaghAkella ,

For question number 1: now it is possible with the new feature of Batch Jobs.

For question number 2: No we do not currently have a rule engine

For question number 3: We are not currently planning any integration on that direction.

Since it is an old issue, I'll close it. Feel free to reopen if more help is needed,

Regards, 

_Alberto_
