### ISSUE TITLE
Custom Date Range Problem

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#845]
When trying to set custom date range for presenting data I found some errors: 

**1)** It is possible to enter negative year.
**2)** Dates till 31.12.1936 are automatically added 100 years (e.g. 1.1.1900 = 1.1.2000, 12.10.1936 = 12.10.2036...).
**3)** Dates from 10.10.2037 are mapped 100 years earlier (e.g. 1.10.2037 = 1.10.1937, 12.11.2042 = 12.11.1942...).
**4)** All dates from 0 - 18xx are mapped to 19xx (e.g. 1810 = 1910, 1712 = 1912...).

**Comment by lorthirk** [comment]
This is due to the time format used in the custom date range dialog. Since it's in a M/d/yy (single-digit month/single digit day/two digit year, e.g. 01/25/18 for January 25th, 2018) it gets wrongly parsed to a Date object by `SimpleDateFormat`. According to the SimpleDateFormat JavaDoc:

> For parsing with the abbreviated year pattern ("y" or "yy"), SimpleDateFormat must interpret the abbreviated year relative to some century. It does this by adjusting dates to be within 80 years before and 20 years after the time the SimpleDateFormat instance is created. For example, using a pattern of "MM/dd/yy" and a SimpleDateFormat instance created on Jan 1, 1997, the string "01/11/12" would be interpreted as Jan 11, 2012 while the string "05/04/64" would be interpreted as May 4, 1964. During parsing, only strings consisting of exactly two digits, as defined by Character.isDigit(char), will be parsed into the default century. Any other numeric string, such as a one digit string, a three or more digit string, or a two digit string that isn't all digits (for example, "-1"), is interpreted literally. So "01/02/3" or "01/02/003" are parsed, using the same pattern, as Jan 2, 3 AD. Likewise, "01/02/-3" is parsed as Jan 2, 4 BC.

I propose to use a more explicit format for the year, using yyyy, and more in general to use the following format for the date and time, already used in Kapua in other sections: `dd/MM/yyyy HH:mm`

@stefanomorson what do you think?

**Comment by lorthirk** [comment]
Should be fixed in [fix-data_date_interval_format](https://github.com/eclipse/kapua/tree/fix-data_date_interval_format)

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that proposed solution fixes this issue.

**Comment by lorthirk** [comment]
Pushed in develop with 1c93c6e0f

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that this issue is resolved.
