### ISSUE TITLE
Device Command Management Execution in Jobs Does Not Work

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#909]
When creating a job with certain commands for a device, the device does not react (to any of the commands given).
If user enters these commands on the device itself (in Kura), there is no problem executing them. 
Commands used: 
 - (sudo) reboot
 - ls 
 - `ping localhost -c 3` (e.g. ping 192.168.1.12 -c 3)
 - pwd 
 - shutdown

Testflow: 
1) Login as kapua-sys
2) Go to Jobs, create new job with parameters: 
   - add selected connected device (e.g. Raspberry Pi)
   - add _Device Command Management Execution_ command (e.g. reboot - look at the screenshot bellow)
3) after applying the settings, select the job and start it. 
**At this point device should restart, but nothing happens**

<img width="1440" alt="screen shot 2017-10-27 at 14 07 19" src="https://user-images.githubusercontent.com/15121999/32103428-9bc30a04-bb20-11e7-8ef2-ccb1d9fd2a2f.png">

Browsers used: 
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

the input parameter must be specified in the serialized form.
e.g.
```
<?xml version="1.0" encoding="UTF-8"?>
<commandInput>
   <command>ping</command>
   <arguments>
   	<argument>8.8.8.8</argument>
   	<argument>-c 3</argument>
   </arguments>
   <timeout>30000</timeout>
</commandInput>
```
This is required because step properties are pluggable and their type is not known by the `JobService` and `JobEngineService`. This constraint makes the serialized parameter usage the only way we currently have found to be able to store on creation and load when the job starts the input properties for the specific `JobStep`.

I've tested this and is currently working. 
Can you please try with this new information?

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Confirmed not a bug
