### ISSUE TITLE
TimeStamp Time And DateRange Time Not Same

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#935]
When setting DateRange in Data, Timestamp time is not the same as DateRange time, because Timestamp time is in Zulu time (look at the screenshot bellow). I know that Timestamp has "Z" in the end, but nevertheless this can be confusing for end users. 

Testflow: 
1. Login as kapua-sys
2. Connect a device with installed ExamplePublisher to Kapua
3. Go to Data and query the results. 

![screen shot 2017-11-08 at 09 06 13](https://user-images.githubusercontent.com/15121999/32538409-359f3d16-c466-11e7-819d-b75839cf0c0b.png)

Browsers used: 
- Google Chrome (Version 62.0.3202.75 (Official Build) (64-bit))
- Safari (Version 11.0.1 (12604.3.5.1.1))
- Mozilla Firefox (56.0.2 (64-bit))
- Opera (Version 48.0.2685.52)

**Comment by ct-goranpalibrk** [comment]
@Coduz @lorthirk @muros-ct @LeoNerdoG In which way we could solve this, because we have several options: 
1) UTC/Zulu time (like we have in Results table in Data view)
2) Local time(as in Data Range)
Because this problem is not only here, should we implement this fix everywhere or in Data view only for now?

**Comment by Coduz** [comment]
It would be possible to have it as `yyyy-mm-ddThh:mm:ss.sss+hh:mm` ? i.e. `2018-01-01T00:11:22+02:00`

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
